### ISSUE TITLE
Issue with high DPI (Retina) displays

### ISSUE THREAD

**Issue by Joolyan** [QuisPic/ae-smooth-zoom#5]
Thanks for develping and sharing this script.

Having just upgraded to an Apple Studio Display, there appears to be an issue with high DPI displays which causes Zoom to display percentage values, half that reported in the After Effects UI. For example, entering 50% in the Zoom UI will display 100% in After Effects. I've also tested on a MacBookPro (not using an external display) running macOS 13.6.3 with After Effects 2014 v24.1 and can reproduce the same issue.

Adding a display multiplier in settings could be a possible solution (if automatic detection not simple) where a multiplier of 1 would be the default and 2 would be used for macOS Retina displays.

Thanks again.

**Comment by QuisPic** [comment]
Hi, sorry for the late reply. Will fix this, thanks for reporting. I've had similar reports, but since I don't have a Retina display, I couldn't figure out what was causing the problem. Yes, a checkbox in the settings for Retina displays might be a possible solution, as I don't think automatic detection is possible.

**Comment by Joolyan** [comment]
Thanks for the update.

Though window.devicePixelRatio is not supported by ExtendScript, there are possible methods to determine Retina displays, but they all come with side effects (eg OS specific, security issues, etc). So I agree that a Retina or High DPI checkbox in settings would be the best solution.

Happy to help with any macOS testing.

**Comment by QuisPic** [comment]
Hi, this should now be fixed in the latest release ([v0.3.0](https://github.com/QuisPic/ae-zoom/releases/tag/v0.3.0)). Can you check?
Enable the checkbox in "Zoom Settings -> General tab -> High DPI display (Retina) support". You can also modify the difference between the UI and the actual values with the "Scale Factor" value under the checkbox.

**Comment by Joolyan** [comment]
Thank you. Enabling "High DPI display (Retina) support" with the default scaling fixed the issue for me.
It's also nice to have a UI to change the preset values, as I find 75% very useful when working on a MacBook.
I'll try the experimental features when I get the opportunity, as I didn't use the plugin with the previous version.

FYI there is a noticable delay when opening Settings, which could be caused by the script searching for the plugin. As the plugin is optional, it might be nice to have an option to disable the plugin. And finally, the gap between the preset text box and the dropdown arrow appears oversized, unless the preset is greater than 1000%

Thanks again for all your hard work.

**Comment by QuisPic** [comment]
I definitely recommend you trying out the plug-in, as the experimental "Maintain view position after zooming" setting works even when you use the script UI to change the zoom.
As for searching for the plug-in, the script already skips the search if the plug-in is not loaded by After Effects. The plug-in sets a flag in the Extendscript environment when it launches, and the script can then check this flag to know immediately if it needs to look for the plug-in. The delay is caused by After Effects drawing all the UI elements of the window, and I don't currently see any way to fix it other than reducing the number of UI elements.

**Comment by Joolyan** [comment]
The delay isn't much of an issue, as it doesn't affect the script's normal use. I was considering suggesting the hiding of UI elements related to the plugin. However, since installing the plugin is recommended, that's not a viable solution.
I'll try the plugin the next time I use AE.
